name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: flake8

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Buid
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest

  notify-teams:
      runs-on: ubuntu-latest
      steps:
        - name: Send Teams Notification
          run: |
            curl -H "Content-Type: application/json" \
                 -d "{\"title\": \"New Pull Request\", \"text\": \"A new PR titled '${{ github.event.pull_request.title }}' was opened by ${{ github.event.pull_request.user.login }} in ${{ github.repository }}. [Check it out](${{ github.event.pull_request.html_url }})!\"}" \
                 "${{ secrets.TEAMS_WEBHOOK }}"